apiVersion: v1
kind: Service
metadata:
  name: grade-submission-api
  namespace: grade-submission
spec:
  selector:
    app.kubernetes.io/instance: grade-submission-api # This links the service to the Pods to route traffic to.
  type: ClusterIP # Exposes the service on a cluster-internal IP. Choosing this value makes your service only reachable from within the cluster.
  # also makes the pod reachable throught the service name and port http://grade-submission-api:3000
  # other types are NodePort and LoadBalancer
   
  ports:
  - port: 3000 # The port that the service will expose inside the cluster.
    targetPort: 3000 # The port that the container is listening on.
