apiVersion: v1
kind: Pod
metadata: # this holds the pod datails
  name: grade-submission-portal
  labels: # Properly grouping and categorizing the pod for easy querrying 
    app.kubernetes.io/name: grade-submission # Group label
    app.kubernetes.io/component: frontend #what this container use for
    app.kubernetes.io/instance: grade-submission-portal #unique name of this container
spec:
  containers: # this holds the container details
  - name: grade-submission-portal # in 1:1 pod:container both should have the same name
    image: rslim087/kubernetes-course-grade-submission-portal
    resources:
      requests: #Kubernetes will decide which node to accomodate our pod base on the resource 
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "128Mi"
        #we dont limit cpu because the kernel can throttle the cpu usage, unlike memory
    ports:
      - containerPort: 5001 #Check the image what port it is exposing
