apiVersion: v1
kind: Secret
metadata:
  name: grade-submission-api-secret
  namespace: grade-submission
type: Opaque
data: # base64 encoded values, in terminal run the command >echo -n 'yourSensitiveString' | base64 
  MONGODB_USER: 'YWRtaW4=' # base64 encoded value of 'admin'
  MONGODB_PASSWORD: 'cGFzc3dvcmQxMjM=' # base64 encoded value of 'password123