apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: grade-submission 
spec:
  selector:
    app.kubernetes.io/instance: mongodb # this is the label we want to match with the pods
  ports:
  - port: 27017 # this is the port we want to expose the service on, which is the default port for MongoDB
    targetPort: 27017 # this is the port we want to forward the traffic to, which is the same as the port we exposed in the container
