apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: grade-submission
type: Opaque
data: # base64 encoded values, in terminal run the command >echo -n 'yourSensitiveString' | base64
  MONGO_INITDB_ROOT_USERNAME: 'YWRtaW4=' # base64 encoded value of 'admin'
  MONGO_INITDB_ROOT_PASSWORD: 'cGFzc3dvcmQxMjM=' # base64 encoded value of 'password123